name: minimalist-webservers
services:
    bash:
        container_name: mws-bash
        image: mws-bash
        pull_policy: never
        build:
            context: bash
            dockerfile: Dockerfile
        ports:
            - 6900:8080
    c:
        container_name: mws-c
        image: mws-c
        pull_policy: never
        build:
            context: c
            dockerfile: Dockerfile
        ports:
            - 6901:8080
    rust:
        container_name: mws-rust
        image: mws-rust
        pull_policy: never
        build:
            context: rust
            dockerfile: Dockerfile
        ports:
            - 6902:8080
